<?php
/**
 * Created by JetBrains PhpStorm.
 * User: dustin
 * Date: 18/07/13
 * Time: 9:09 PM
 * To change this template use File | Settings | File Templates.
 */

namespace ZF2Deploy\Plugin\Db;


use ZF2Deploy\Plugin\AbstractPlugin;
use ZF2Deploy\Plugin\OutputGeneratingPlugin;

/**
 * Class DoctrineMigrationView
 * @package ZF2Deploy\Plugin\Db
 *
 * Plugin to display the SQL that is required to upgrade the database.
 */
class DoctrineMigrationView extends AbstractPlugin implements OutputGeneratingPlugin
{

    /**
     * Runs the plugin
     * @return void
     */
    function run()
    {
        // TODO: Implement run() method.
    }

    /**
     * Gets the output generated by a plugin.
     * @return string
     */
    public function getOutput()
    {
        return "null";
    }
}